# 서버 설정
server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# Spring 애플리케이션 설정
spring:
  application:
    name: H2 Practice Application

  # H2 DB 설정 (In-memory Mode)
  datasource:
    # H2 인메모리 데이터베이스 연결 URL
    # mem:testdb = 메모리에 'testdb'라는 이름의 DB 생성
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver # H2 데이터베이스 드라이버 클래스
    username: sa  # DB 접속 계정(H2 기본값)
    password:     # DB 접속 비밀번호(H2 기본값 : 비어있음)

  # H2 웹 콘솔 설정
  h2:
    console:
      enabled: true         # H2 웹 콘솔 활성화(브라우저에서 DB 조회 가능)
      path: /h2-console

  # JPA 설정
  jpa:
    # 앱 시작시 schema.sql, data.sql 초기 데이터 세팅을 위한 설정
    defer-datasource-initialization: true

    hibernate:
      # DDL(Data Definition Language) 자동 실행 정책
      ddl-auto : create-drop # 시작할 때 생성, 종료할 때 삭제(테스트용)
      # ddl-auto : update # 변경된 스키마만 업데이트(개발용)

    # JPA 쿼리 로깅 설정
    show-sql: true #실행되는 SQL 쿼리를 콘솔에 출력

    properties:
      hibernate:
        format_sql: true # SQL 뭐리를 보기 좋게 포맷팅
        use_sql_comments: true # SQL에 주석 추가

  # SQL 초기화 설정
  sql:
    init:
      # 스키마 초기화 모드
      mode: always